---

- name: Ensure rsyslogd folder exists
  file: >
    path="{{ papertrail_app_rsyslogd_path }}"
    state=directory
    owner=root
    group=root
    mode=0751

- name: Install rsyslog-gnutls on Ubuntu
  apt: name=rsyslog-gnutls state=latest
  when: ansible_pkg_mgr == 'apt'

- name: Install rsyslog-gnutls on CentOS/RH
  yum: name=rsyslog-gnutls state=latest
  when: ansible_pkg_mgr == 'yum'

- name: Download papertrailapp CA bundle
  get_url: >
    url="{{ papertrail_app_ca_bundle }}"
    dest="{{ papertrail_app_ca_path }}"
    mode=0644

- name: Validate the checksum of the file
  stat: >
    path="{{ papertrail_app_ca_path }}"
    get_md5=true
  register: papertrail_ca

- fail: msg="Checksum doesn't match!"
  when: papertrail_ca.stat.md5 != "{{ papertrail_app_ca_checksum }}"

- name: Add papertrailapp to rsyslog
  template: >
    src='rsyslog.j2'
    dest="{{ papertrail_app_rsyslogd_path }}/papertrail"
    owner='root'
    group='root'
    mode=0644


- name: Add papertrailapp to rsyslog
  lineinfile: >
    line="$IncludeConfig {{ papertrail_app_rsyslogd_path }}/papertrail"
    state=present
    insertafter=EOF
    dest="/etc/rsyslog.conf"

- name: Restart rsyslog
  service: >
    name='rsyslog'
    state='restarted'
...
