# Set up a simple sudoers file
---
- include: install.yml

- name: Copying, Verifying and placing sudo file
  template: >
    src="{{ sudo_sudoers_template | mandatory }}"
    dest=/etc/sudoers
    owner=root
    group=root
    mode=0640
    validate='visudo -cf %s'
...
