---
- name: Ensure that curl is installed via apt
  apt:  >
        name='curl'
        state='latest'
  when: ansible_pkg_mgr == 'apt'

- name: Ensure that curl is installed via yum
  yum:  >
        name='curl'
        state='latest'
  when: ansible_pkg_mgr == 'yum'
...
