---

- include: do.yml
- include: rax.yml

- hosts: provision
  remote_user: root
  gather_facts: false
  tasks:
  - name: Wait for port 22 to become available.
    local_action: >
      wait_for
      port=22
      host="{{ ansible_ssh_host }}"
      timeout=300
      delay=30

- hosts: provision
  roles:
  - { role: security }
  - { role: monitoring }

- hosts: qualysguard
  connection: local
  gather_facts: false
  roles:
  - { role: qualysguard }
...
