---
- hosts: rackspace-cloud
  connection: local
  gather_facts: false
  vars_files:
    - vault.yml
  vars:
    client_id: 'wibble'
    ssh_provisioning_public_key_name: 'Inviqa Deploy'
  roles:
    - { role: rackspace-cloud }
  tasks:
    - name: Register the box
      local_action:
        module:      rax_facts
        api_key:     "bbb3943746f0d83ec9102333c4a9c716"
        username:    "leftfielddigital"
        name:        "{{ inventory_hostname }}"
        region:      "{{ rackspace_cloud_region | default('DFW') }}"
        tenant_id:   "425037"
        group:       "{{ client_id }}"
      register:      rax

    - name: Add new host to our inventory.
      add_host: >
        name="{{ inventory_hostname }}"
        ansible_ssh_host="{{ item.rax_accessipv4 }}"
        hostname="{{ inventory_hostname }}"
        groups=provision
      with_items: rax

...
