---
- src:     https://github.com/shrikeh/ansible-sudo.git
  name:    role_sudo

- src:      goozbach.EPEL
- src:      bennojoy.ntp
- src:      opsmatic.opsmatic
- src:      avelis.dome9
- src:      debops.rsyslog
- src:      resmo.fail2ban
...
