---
rackspace_provisioning_public_key:  'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQCzjn/8gqQwXJoZg6bZ2MGLtV+6q/7cZGyXKjLiSLwo7Io7DLV9t9mDGNiVC4+n1Oug+TVnVJedbErdt+OORDHuklUHhJwgLSLgN7TKqIc7f/p2fYr/23Yw6+yjXD+ZLfJ00NW4SPUZVQgEJj6uLLw3Ux1bI83lDVB9H8C4gdD5O5nu05o5JGHPX3mOkHr9gpuvMdCwFjKJNonuwZnhN1Kn4daZx/cyExEF2B1p+R0V82tA1TzRYb9TF0/+LcrXR+o9NtYywmPMrBR1iD//B9gX+NbvATHnQq8yU+oKrGhfF6pSqVE7By+tBw/m21uVmh99TLh6eNWvOxynN/U/BD3bXw0mqjJnLteqFSnolDLX6G5HgN2g59Uu4gnCnkggRNnACwOi7L+FTinHgP/JmwMrUNX89/uzpIBNOMX8GOB4Mk95YL9AHhB80NgUUG/ETOWTWVtqcNSd4d3eokdCsCezXaS0r85rZxTYi+6nLlPcy4fwXo80kuK0bbDRk/B6K9inKH8VVHsoUa84JKsue4Syv7Sklh84R4SPGUnMfl68EcnzKodwJrLwCWlTobuFe1iKu6jJ1qO+E2dghw3ROTEQKVRcCIuiqyeBPfrzLaj37h9e+YFSSZeCeq7jrz/i3AUJVKzSHxfBkxv4BdP37xBkDMZu3npghQfdrYqKkqDsB6f8pY1xz5pitk+F/F8xKlcl6Y4RQ/ssZfm94iIQeDxCcqi3S5RcUsaf5fn+nVXSMua31rTMkNvExLnWN5S16c0BA/yTP7KrkVQTAoIHWbwWQVgu7VM5Bib9622W38iIen7TnmMO150V5c3QnrOS2xgBS9IT5uwKrWagEfl0+RPMiPB4TLZckQHB1ZiYT8TpSEtwCCknIhl/RyalhO8yMZo+5k+GutBPu3lPnf45fdPfKne0W0JbFOr+EX0qF6+wwfGFugdjhCu+I/Qvq0MOMgtjehJ/UjF9CjMDfykl85iZas9G1nChBk7ZFn6czkU7SDzFOipN8HZqrGSNvyJQVMAJAL46zXTr8gjZjUZ9ZdbrY0aGlG5TwJEWCqBUopo4HADAOQioxRaqR4ZWiwqwf5o1DAqUC21yzFPfvJDhpNPuZoSXLwbcE5yGj4WQg+c3PgJCt4rwY5qDYbHXer8y+pfMQ87aYxSpUwIpcMiNUN0RKdbyh1BarCuh0WuTjCrdNvDM/rvQySb95mqJPefEBAsdIplpVz59J99SDIRc9Kl/vzDwETHb1NnVS/9OjyU9XfmfRc3APDHFYr1/54wFnwO83rTXJiXVXss2hW+QKljV8ubG+DnFhd7krZI5bXCIFFUv2aWa2FmVDNUbSfs/me9TiFz6SanYhzm2uxqeXhpp bhanlon@inviqa.com:default'
rackspace_cloud_auth_endpoint:      'https://identity.api.rackspacecloud.com/v2.0/'
rackspace_cloud_ssh_key_name:       'inviqa_ansible'
rackspace_cloud_autoincrement:      true
rackspace_cloud_count:              1
rackspace_cloud_count_offset:       1
rackspace_cloud_disk_config:        manual
rackspace_cloud_identity_type:      rackspace
rackspace_cloud_region_id:          DFW

rackspace_images:
  centos6:
    pv:       '619fe497-803b-4a0e-bf8a-fd4e2970b4c1'
    pvhvm:    '6b025595-a83b-436b-b37d-d5b212b5ddfc'
  rhel5:
    pv:       'a8552c7e-ebc2-48c0-ad00-be56fb29b302'
  rhel6:
    pv:       'a1555bbc-c779-4b85-a6ec-5f53b7b924be'
    pvhvm:    '14369199-08bf-4ac0-8bc0-d9e9881bdad4'
  rhel7:
    pvhvm:    'ff28d854-3edd-4bad-9897-e457e8b1e849'
  ubuntu1204:
    pv:       '1e974b12-95f5-4e4f-bc0d-203f1e34ad65'
    pvhvm:    'ca9ab240-5fe5-43a4-b936-7dc5009cc67f'
  ubuntu1404:
    pv:       'adb78bf4-81ae-4dce-a417-8eb2b7f7f0c3'
    pvhvm:    '6f29d6a6-9972-4ae0-aa80-040fa2d6a9cf'
  ubuntu:
    pvhvm:    'c1a96aed-e867-47ef-9f38-0be158eb98b8'
  debian7:
    pvhvm:    'e3ee670e-61eb-4f00-8e18-eec91cc37481'
  debian8:
    pvhvm:    '78d48afe-a94e-4fbe-9c39-ff382479d0a9'


rackspace_flavors:
  512_standard:
    id: 2
    name: 512MB Standard Instance
  1gb_standard:
    id: 3
    name: 1GB Standard Instance
  2gb_standard:
    id: 4
    name: 2GB Standard Instance
  4gb_standard:
    id: 5
    name: 4GB Standard Instance
  8gb_standard:
    id: 8
    name: 8GB Standard Instance
  15gb_standrd:
    id: 7
    name: 15GB Standard Instance
  30gb_standrd:
    id: 8
    name: 30GB Standard Instance
  performance1_1:
    id:  performance1-1
    name: 1 GB Performance
  performance1_2:
    id:  performance1-2
    name: 2 GB Performance
  performance1_4:
    id:  performance1-4
    name: 4 GB Performance
  performance1_8:
    id:  performance1-8
    name: 8 GB Performance


rackspace_magento_pipeline: &magento_pipeline
  image: "{{ rackspace_images.centos6.pvhvm }}"
  flavor: "{{ rackspace_flavors.performance1_4 }}"
...
