---
- name: Create new Droplet.
  digital_ocean: >
    state=present
    command=droplet
    name="{{ hostname_name | mandatory }}"
    private_networking=yes
    client_id="{{ digital_ocean_v1_client_id | mandatory }}"
    api_key="{{ digital_ocean_v1_api_key | mandatory }}"
    size_id="{{ digital_ocean_size_id | mandatory }}"
    image_id="{{ digital_ocean_image_id | mandatory }}"
    region_id="{{ digital_ocean_region_id | mandatory }}"
    ssh_key_ids="{{ digital_ocean_ssh_key_ids | mandatory }}"
    unique_name=yes
  register: do

- name: Add new host to our inventory.
  add_host:
    name: "{{ do.droplet.ip_address }}"
    groups: do
  when: do.droplet is defined
...
