---
sudo_sudoers_dir_mode: '0750'

sudo_groups:
  - gid: "{{ sudo_group_gids.inviqasupport | mandatory }}"
    filename: inviqa-support
    permissions: 'ALL=(ALL:ALL) NOPASSWD: ALL'
  - gid: "{{ sudo_group_gids.inviqaoohsupport | mandatory }}"
    filename: inviqa-support-ooh
    permissions: 'ALL=(ALL:ALL) ALL'
  - gid: "{{ sudo_group_gids.admin | mandatory }}"
    filename: inviqa-admin
    permissions: 'ALL=(ALL:ALL) NOPASSWD: ALL'
  - gid: "{{ sudo_group_gids.provision | mandatory }}"
    filename: inviqa-provisioning
    permissions: 'ALL=(root) NOPASSWD: ALL'
  - gid: "{{ sudo_group_gids.deploy | mandatory }}"
    filename: inviqa-deploy
    permissions: 'ALL=(deploy) NOPASSWD: ALL'
...
