---
- name: Check if JumpCloud is already installed
  stat:
    path: /opt/jc
  register: jc_installed

- name:   Update time
  shell:  "ntpdate -u pool.ntp.org"

- name: Install JumpCloud
  shell: "curl --header 'x-connect-key: {{ jumpcloud_x_connect_key | mandatory }}' {{ jumpcloud_x_connect_url | mandatory }} | bash"
  when: "not jc_installed.isdir"

- name: Restart the JCagent
  service: name=jcagent state=restarted
  when: "not jc_installed.isdir"
...
