---
- name: Check if JumpCloud is already installed
  shell: "[ -d /opt/jc ] && echo 'Found' || echo ''"
  register: jc_installed

- name:   Update time
  shell:  "ntpdate -u pool.ntp.org"

- name: Install JumpCloud
  shell: "curl --header 'x-connect-key: {{ jumpcloud_x_connect_key | mandatory }}' {{ jumpcloud_x_connect_url | mandatory }} | bash"
  when: "not jc_installed.stdout"

- name: Restart the JCagent
  service: name=jcagent state=restarted
  when: "not jc_installed.stdout"
...
