- name: Test if this is the first installation
  stat: path=/var/db/opsmatic-agent/data
  register: opsmatic_data

- name: Perform initial agent configuration
  command: /usr/bin/config-opsmatic-agent --token={{ opsmatic_integration_token }} --opsmatic_http={{ opsmatic_auth_http }}
  when: opsmatic_data.stat.isdir is not defined

- name: Enable and start the Opsmatic Agent
  service: name=opsmatic-agent state=started
