---
- name: Add the groups to sudoers.d
  template: >
    src='deploy.j2'
    dest="/etc/sudoers.d/{{ item.name }}"
    owner='root'
    group='root'
    mode='0640'
    validate='visudo -cf %s'
  with_items:
      sudo_groups
...
