---
- name: Create the groups for the environment
  group:
    name:   "{{ item.name }}"
    gid:    "{{ item.gid }}"
    state:  present
  with_items: user_groups_environment
  when: user_groups_environment is defined
...
