---
- name: Install fail2ban
  include: install.yml

- name: Put the local jail in place
  template: >
    dest="{{ fail2ban_localjail_path | default('/etc/fail2ban/jail.local') }}"
    src="{{ fail2ban_localjail_template | default('jail.local.j2') }}"
    owner="{{ fail2ban_localjail_owner | default('root') }}"
    group="{{ fail2ban_localjail_group | default('root') }}"
    mode="{{ fail2ban_localjail_mode | default('0600') }}"
...
