---
- src:      ajsalminen.hosts
- src:      shrikeh.facl
- src:      goozbach.EPEL
- src:      bennojoy.ntp
- src:      opsmatic.opsmatic
- src:      avelis.dome9
- src:      debops.rsyslog
- src:      resmo.fail2ban
- src:      Rackor3000.sudo
  name:     role_sudo
- src:      DrMegahertz.cloudflare
...
