---
do_size_id:                 63
do_image_id:                11836690
do_region_id:               7
do_unique_name:             yes
do_backups_enabled:         yes
do_private_networking:      yes
...
