---
- debug:
    var: ansible_version

- name: Find out which type of config is present for logging
  stat:
    path: /etc/ryslog.conf
  register: papertrailapp_rsyslog
  tags: papertrailapp

- include: rsyslog.yml
  when: papertrailapp_rsyslog.stat.exists is defined and papertrailapp_rsyslog.stat.exists
  tags: papertrailapp
...
