---

- name: Get assets from Qualys
  uri: >
    url="{{ qualysguard_platform }}/api/2.0/fo/asset/group/?action=list"
    method='GET'
    user='nvqa-bh'
    password='Yy9LT2YQ37B8VXCKyMpp2tMkB6bvaHHcC2CY2dZZ'
    HEADER_X-Requested-With='ansible'
    return_content=yes
    force_basic_auth=yes
  register: assets

- name: Display output from Qualys
  debug: var="{{ assets.content }}"
...
